import { NextRequest, NextResponse } from 'next/server';
import { collection, query, where, orderBy, limit as queryLimit, getDocs, Timestamp, getDoc, doc } from 'firebase/firestore';
import { db } from '@/lib/firebase';

export async function GET(request: NextRequest) {
  try {
    // TODO: Add proper admin authentication in production
    // For now, we'll allow access for debugging
    
    // Get API usage statistics
    const stats = {
      supadata: {
        monthlyLimit: 1000, // Based on Starter plan (adjust if different)
        currentUsage: 102, // Hardcoded current usage from SupaData dashboard
        lastReset: null as Date | null,
        recentErrors: [] as any[]
      },
      searchapi: {
        monthlyLimit: 100, // Adjust based on your plan
        currentUsage: 0,
        lastReset: null as Date | null,
        recentErrors: [] as any[]
      },
      youtube: {
        dailyQuota: 10000, // YouTube API daily quota
        currentUsage: 0,
        lastReset: null as Date | null,
        recentErrors: [] as any[]
      },
      cache: {
        totalCached: 0,
        totalHits: 0,
        totalMisses: 0,
        popularVideos: [] as any[]
      }
    };

    // Get transcript cache statistics
    if (db) {
      try {
        const cacheCollection = collection(db, 'transcriptCache');
        const cacheQuery = query(
          cacheCollection,
          orderBy('accessCount', 'desc'),
          queryLimit(10)
        );
        
        const cacheSnapshot = await getDocs(cacheQuery);
        stats.cache.totalCached = cacheSnapshot.size;
        
        cacheSnapshot.forEach((doc) => {
          const data = doc.data();
          stats.cache.totalHits += data.accessCount || 0;
          
          // Try to determine the extraction method from metadata
          let method = 'unknown';
          if (data.metadata?.method) {
            method = data.metadata.method;
          } else if (data.metadata?.isAutoGenerated !== undefined) {
            // If we have isAutoGenerated flag, it might be from YouTube or SearchAPI
            method = data.metadata.isAutoGenerated ? 'youtube-auto' : 'youtube-manual';
          }
          
          stats.cache.popularVideos.push({
            id: doc.id,
            title: data.videoTitle,
            url: data.videoUrl,
            accessCount: data.accessCount,
            language: data.language,
            method: method,
            createdAt: data.createdAt?.toDate()
          });
        });
      } catch (cacheError) {
        console.error('Error fetching cache stats:', cacheError);
      }

      // Get API usage logs (you would need to implement logging in the extraction route)
      try {
        const logsCollection = collection(db, 'apiUsageLogs');
        
        // Get today's usage
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        
        const todayQuery = query(
          logsCollection,
          where('timestamp', '>=', Timestamp.fromDate(today)),
          orderBy('timestamp', 'desc')
        );
        
        const todaySnapshot = await getDocs(todayQuery);
        
        todaySnapshot.forEach((doc) => {
          const data = doc.data();
          if (data.api === 'supadata') {
            stats.supadata.currentUsage++;
            if (data.error) {
              stats.supadata.recentErrors.push({
                error: data.error,
                timestamp: data.timestamp?.toDate()
              });
            }
          } else if (data.api === 'searchapi') {
            stats.searchapi.currentUsage++;
            if (data.error) {
              stats.searchapi.recentErrors.push({
                error: data.error,
                timestamp: data.timestamp?.toDate()
              });
            }
          } else if (data.api === 'youtube') {
            stats.youtube.currentUsage++;
            if (data.error) {
              stats.youtube.recentErrors.push({
                error: data.error,
                timestamp: data.timestamp?.toDate()
              });
            }
          }
        });
      } catch (logsError) {
        console.error('Error fetching API logs:', logsError);
      }
    }

    // Calculate usage percentages
    const usagePercentages = {
      supadata: (stats.supadata.currentUsage / stats.supadata.monthlyLimit) * 100,
      searchapi: (stats.searchapi.currentUsage / stats.searchapi.monthlyLimit) * 100,
      youtube: (stats.youtube.currentUsage / stats.youtube.dailyQuota) * 100,
      cacheHitRate: stats.cache.totalCached > 0 
        ? (stats.cache.totalHits / (stats.cache.totalHits + stats.cache.totalMisses)) * 100
        : 0
    };

    return NextResponse.json({
      success: true,
      stats,
      usagePercentages,
      recommendations: generateRecommendations(stats, usagePercentages)
    });

  } catch (error) {
    console.error('API usage stats error:', error);
    return NextResponse.json(
      { 
        error: 'Failed to get API usage stats',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

function generateRecommendations(stats: any, percentages: any): string[] {
  const recommendations = [];

  if (percentages.supadata > 80) {
    recommendations.push('⚠️ SupaData usage is above 80%. Consider upgrading plan or relying more on cache.');
  }

  if (percentages.supadata >= 100) {
    recommendations.push('🚨 SupaData limit reached! Fallback methods will be used for new videos.');
  }

  if (stats.cache.totalCached < 100) {
    recommendations.push('💡 Build up your transcript cache by processing popular Japanese videos.');
  }

  if (percentages.cacheHitRate < 50) {
    recommendations.push('📈 Low cache hit rate. Consider pre-caching popular content.');
  }

  if (stats.supadata.recentErrors.length > 5) {
    recommendations.push('⚠️ Multiple SupaData errors detected. Check API key and service status.');
  }

  return recommendations;
}