import { Achievement } from './types';

// Default achievements that come with the system
export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  // Streak Achievements
  {
    id: 'first_day',
    category: 'streaks',
    title: 'First Steps',
    description: 'Complete your first day of study',
    icon: '🌱',
    color: '#10b981',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 50,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'complex',
    // Will be checked with custom logic - requires at least 1 drill/game/study session
    minActivityRequirement: true
  },
  {
    id: 'streak_3',
    category: 'streaks',
    title: 'Getting Started',
    description: 'Study for 3 consecutive days',
    icon: '🔥',
    color: '#f59e0b',
    rarity: 'common',
    rewardType: 'title',
    rewardValue: 'Dedicated Learner',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'currentStreak',
    conditionOperator: '>=',
    conditionValue: 3
  },
  {
    id: 'streak_7',
    category: 'streaks',
    title: 'Week Warrior',
    description: 'Study for 7 consecutive days',
    icon: '⚡',
    color: '#3b82f6',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Week Warrior',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'currentStreak',
    conditionOperator: '>=',
    conditionValue: 7
  },
  {
    id: 'streak_30',
    category: 'streaks',
    title: 'Monthly Master',
    description: 'Study for 30 consecutive days',
    icon: '👑',
    color: '#8b5cf6',
    rarity: 'epic',
    rewardType: 'title',
    rewardValue: 'Monthly Master',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'currentStreak',
    conditionOperator: '>=',
    conditionValue: 30
  },
  {
    id: 'streak_100',
    category: 'streaks',
    title: 'Centurion',
    description: 'Study for 100 consecutive days',
    icon: '🏆',
    color: '#fbbf24',
    rarity: 'legendary',
    rewardType: 'title',
    rewardValue: 'Centurion',
    requiredUserType: 'premium',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'currentStreak',
    conditionOperator: '>=',
    conditionValue: 100
  },

  // Drill Achievements
  {
    id: 'drill_first',
    category: 'drills',
    title: 'First Drill',
    description: 'Complete your first drill session',
    icon: '📝',
    color: '#06b6d4',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 25,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'drillsCompleted',
    conditionOperator: '>=',
    conditionValue: 1
  },
  {
    id: 'drill_10',
    category: 'drills',
    title: 'Drill Novice',
    description: 'Complete 10 drill sessions',
    icon: '🎯',
    color: '#10b981',
    rarity: 'common',
    rewardType: 'badge',
    rewardValue: 'drill_novice_badge',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'drillsCompleted',
    conditionOperator: '>=',
    conditionValue: 10
  },
  {
    id: 'drill_50',
    category: 'drills',
    title: 'Drill Enthusiast',
    description: 'Complete 50 drill sessions',
    icon: '🎪',
    color: '#f59e0b',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Drill Enthusiast',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'drillsCompleted',
    conditionOperator: '>=',
    conditionValue: 50
  },
  {
    id: 'drill_100',
    category: 'drills',
    title: 'Drill Master',
    description: 'Complete 100 drill sessions',
    icon: '🥋',
    color: '#8b5cf6',
    rarity: 'epic',
    rewardType: 'title',
    rewardValue: 'Drill Master',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'drillsCompleted',
    conditionOperator: '>=',
    conditionValue: 100
  },

  // Word Collection Achievements
  {
    id: 'word_collector_10',
    category: 'words',
    title: 'Word Collector',
    description: 'Save 10 words to your lists',
    icon: '📚',
    color: '#06b6d4',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 30,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'wordsSaved',
    conditionOperator: '>=',
    conditionValue: 10
  },
  {
    id: 'word_collector_100',
    category: 'words',
    title: 'Vocabulary Builder',
    description: 'Save 100 words to your lists',
    icon: '📖',
    color: '#10b981',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Vocabulary Builder',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'wordsSaved',
    conditionOperator: '>=',
    conditionValue: 100
  },
  {
    id: 'word_collector_500',
    category: 'words',
    title: 'Word Hoarder',
    description: 'Save 500 words to your lists',
    icon: '📚',
    color: '#8b5cf6',
    rarity: 'epic',
    rewardType: 'title',
    rewardValue: 'Word Hoarder',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'wordsSaved',
    conditionOperator: '>=',
    conditionValue: 500
  },

  // Reading Achievements
  {
    id: 'reader_10',
    category: 'reading',
    title: 'Bookworm',
    description: 'Read 10 sentences',
    icon: '🐛',
    color: '#10b981',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 40,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'sentencesRead',
    conditionOperator: '>=',
    conditionValue: 10
  },
  {
    id: 'reader_100',
    category: 'reading',
    title: 'Reading Enthusiast',
    description: 'Read 100 sentences',
    icon: '📰',
    color: '#f59e0b',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Reading Enthusiast',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'sentencesRead',
    conditionOperator: '>=',
    conditionValue: 100
  },

  // Story Achievements
  {
    id: 'story_first',
    category: 'stories',
    title: 'Story Explorer',
    description: 'Complete your first story',
    icon: '📜',
    color: '#06b6d4',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 75,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'storiesCompleted',
    conditionOperator: '>=',
    conditionValue: 1
  },
  {
    id: 'story_10',
    category: 'stories',
    title: 'Story Lover',
    description: 'Complete 10 stories',
    icon: '📚',
    color: '#8b5cf6',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Story Lover',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'storiesCompleted',
    conditionOperator: '>=',
    conditionValue: 10
  },

  // Game Achievements
  {
    id: 'gamer_first',
    category: 'games',
    title: 'Game On',
    description: 'Play your first game',
    icon: '🎮',
    color: '#f59e0b',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 35,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'gamesPlayed',
    conditionOperator: '>=',
    conditionValue: 1
  },
  {
    id: 'gamer_25',
    category: 'games',
    title: 'Game Master',
    description: 'Play 25 games',
    icon: '🏆',
    color: '#8b5cf6',
    rarity: 'epic',
    rewardType: 'title',
    rewardValue: 'Game Master',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'gamesPlayed',
    conditionOperator: '>=',
    conditionValue: 25
  },

  // Kanji Achievements
  {
    id: 'kanji_first',
    category: 'learning',
    title: 'Kanji Explorer',
    description: 'Study your first kanji',
    icon: '🈷️',
    color: '#ef4444',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 50,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'kanjiStudied',
    conditionOperator: '>=',
    conditionValue: 1
  },
  {
    id: 'kanji_10',
    category: 'learning',
    title: 'Kanji Student',
    description: 'Study 10 kanji',
    icon: '🉐',
    color: '#f59e0b',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 100,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'kanjiStudied',
    conditionOperator: '>=',
    conditionValue: 10
  },
  {
    id: 'kanji_50',
    category: 'learning',
    title: 'Kanji Scholar',
    description: 'Study 50 kanji',
    icon: '🈲',
    color: '#10b981',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Kanji Scholar',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'kanjiStudied',
    conditionOperator: '>=',
    conditionValue: 50
  },
  {
    id: 'kanji_100',
    category: 'learning',
    title: 'Kanji Expert',
    description: 'Study 100 kanji',
    icon: '🈸',
    color: '#3b82f6',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Kanji Expert',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'kanjiStudied',
    conditionOperator: '>=',
    conditionValue: 100
  },
  {
    id: 'kanji_500',
    category: 'learning',
    title: 'Kanji Master',
    description: 'Study 500 kanji',
    icon: '㊙️',
    color: '#8b5cf6',
    rarity: 'epic',
    rewardType: 'title',
    rewardValue: 'Kanji Master',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'kanjiStudied',
    conditionOperator: '>=',
    conditionValue: 500
  },
  {
    id: 'kanji_1000',
    category: 'learning',
    title: 'Kanji Sensei',
    description: 'Study 1000 kanji',
    icon: '🎌',
    color: '#fbbf24',
    rarity: 'legendary',
    rewardType: 'title',
    rewardValue: 'Kanji Sensei',
    requiredUserType: 'premium',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'kanjiStudied',
    conditionOperator: '>=',
    conditionValue: 1000
  },



  // Multi-Level Achievement: Streak Master
  {
    id: 'streak_master',
    category: 'streaks',
    title: 'Streak Master',
    description: 'Master the art of consistent study',
    icon: '🔥',
    color: '#f59e0b',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 50,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'currentStreak',
    conditionOperator: '>=',
    conditionValue: 1, // Base condition for multi-level achievements
    isMultiLevel: true,
    levels: [
      {
        level: 1,
        title: 'Streak Starter',
        description: 'Study for 1 day',
        icon: '🌱',
        targetValue: 1,
        rewardType: 'xp',
        rewardValue: 50,
        rarity: 'common'
      },
      {
        level: 2,
        title: 'Streak Builder',
        description: 'Study for 5 days',
        icon: '🔥',
        targetValue: 5,
        rewardType: 'xp',
        rewardValue: 100,
        rarity: 'common'
      },
      {
        level: 3,
        title: 'Streak Warrior',
        description: 'Study for 15 days',
        icon: '⚡',
        targetValue: 15,
        rewardType: 'title',
        rewardValue: 'Streak Warrior',
        rarity: 'rare'
      },
      {
        level: 4,
        title: 'Streak Legend',
        description: 'Study for 50 days',
        icon: '👑',
        targetValue: 50,
        rewardType: 'cosmetic',
        rewardValue: 'golden_streak_frame',
        rarity: 'epic'
      },
      {
        level: 5,
        title: 'Streak Immortal',
        description: 'Study for 365 days',
        icon: '🏆',
        targetValue: 365,
        rewardType: 'cosmetic',
        rewardValue: 'immortal_aura',
        rarity: 'legendary'
      }
    ]
  },

  // Multi-Level Achievement: Word Collector
  {
    id: 'word_master',
    category: 'words',
    title: 'Word Master',
    description: 'Build an impressive vocabulary collection',
    icon: '📚',
    color: '#06b6d4',
    rarity: 'common',
    rewardType: 'xp',
    rewardValue: 30,
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'wordsSaved',
    conditionOperator: '>=',
    conditionValue: 1,
    isMultiLevel: true,
    levels: [
      {
        level: 1,
        title: 'Word Seeker',
        description: 'Save 10 words',
        icon: '📖',
        targetValue: 10,
        rewardType: 'xp',
        rewardValue: 30,
        rarity: 'common'
      },
      {
        level: 2,
        title: 'Word Collector',
        description: 'Save 50 words',
        icon: '📚',
        targetValue: 50,
        rewardType: 'xp',
        rewardValue: 75,
        rarity: 'common'
      },
      {
        level: 3,
        title: 'Word Enthusiast',
        description: 'Save 200 words',
        icon: '📝',
        targetValue: 200,
        rewardType: 'title',
        rewardValue: 'Word Enthusiast',
        rarity: 'rare'
      },
      {
        level: 4,
        title: 'Word Scholar',
        description: 'Save 1000 words',
        icon: '🎓',
        targetValue: 1000,
        rewardType: 'cosmetic',
        rewardValue: 'scholar_badge',
        rarity: 'epic'
      },
      {
        level: 5,
        title: 'Word Sage',
        description: 'Save 5000 words',
        icon: '🧙‍♂️',
        targetValue: 5000,
        rewardType: 'cosmetic',
        rewardValue: 'sage_aura',
        rarity: 'legendary'
      }
    ]
  },

  // Hidden/Easter Egg Achievements
  {
    id: 'early_bird',
    category: 'hidden',
    title: 'Early Bird',
    description: 'Study before 6 AM',
    icon: '🐦',
    color: '#fbbf24',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Early Bird',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'hidden',
    isHidden: true,
    unlockHint: 'Rise with the sun...'
  },
  {
    id: 'night_owl',
    category: 'hidden',
    title: 'Night Owl',
    description: 'Study after 11 PM',
    icon: '🦉',
    color: '#6366f1',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Night Owl',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'hidden',
    isHidden: true,
    unlockHint: 'When the world sleeps...'
  },
  {
    id: 'weekend_warrior',
    category: 'hidden',
    title: 'Weekend Warrior',
    description: 'Study on both Saturday and Sunday',
    icon: '⚔️',
    color: '#8b5cf6',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Weekend Warrior',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'hidden',
    isHidden: true,
    unlockHint: 'Even when others rest...'
  },
  {
    id: 'speed_demon',
    category: 'hidden',
    title: 'Speed Demon',
    description: 'Complete 10 drills in under 30 minutes',
    icon: '💨',
    color: '#ef4444',
    rarity: 'epic',
    rewardType: 'cosmetic',
    rewardValue: 'speed_trail',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'hidden',
    isHidden: true,
    unlockHint: 'Lightning fast learning...'
  },

  // XP Milestones
  {
    id: 'xp_1000',
    category: 'hidden',
    title: 'Rising Star',
    description: 'Earn 1000 XP',
    icon: '⭐',
    color: '#fbbf24',
    rarity: 'rare',
    rewardType: 'title',
    rewardValue: 'Rising Star',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'totalXP',
    conditionOperator: '>=',
    conditionValue: 1000
  },
  {
    id: 'xp_5000',
    category: 'hidden',
    title: 'XP Champion',
    description: 'Earn 5000 XP',
    icon: '🌟',
    color: '#8b5cf6',
    rarity: 'epic',
    rewardType: 'title',
    rewardValue: 'XP Champion',
    isActive: true,
    isCustom: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditionType: 'simple',
    conditionField: 'totalXP',
    conditionOperator: '>=',
    conditionValue: 5000
  }
];

// Helper function to get achievements by category
export function getAchievementsByCategory(category: Achievement['category']): Achievement[] {
  return DEFAULT_ACHIEVEMENTS.filter(achievement => achievement.category === category);
}

// Helper function to get achievements by rarity
export function getAchievementsByRarity(rarity: Achievement['rarity']): Achievement[] {
  return DEFAULT_ACHIEVEMENTS.filter(achievement => achievement.rarity === rarity);
}

// Helper function to get achievements available to a user type
export function getAchievementsForUserType(userType: 'guest' | 'free' | 'premium'): Achievement[] {
  return DEFAULT_ACHIEVEMENTS.filter(achievement => 
    !achievement.requiredUserType || achievement.requiredUserType === userType
  );
}