'use client';

import { useEffect, useState } from 'react';
import { TranscriptLine } from '../page';
import { useStrings } from '@/contexts/LanguageContext';
import SubtitleUploader from './SubtitleUploader';

interface TranscriptDisplayProps {
  videoUrl: string;
  audioUrl: string;
  onTranscriptLoaded: (transcript: TranscriptLine[]) => void;
}

export default function TranscriptDisplay({ 
  videoUrl, 
  audioUrl, 
  onTranscriptLoaded 
}: TranscriptDisplayProps) {
  const [status, setStatus] = useState<'idle' | 'loading' | 'completed' | 'error'>('idle');
  const [error, setError] = useState<string | null>(null);
  const strings = useStrings();

  useEffect(() => {
    loadTranscript();
  }, [videoUrl]);

  const loadTranscript = async () => {
    setStatus('loading');
    setError(null);

    try {
      // For YouTube player mode, try to extract subtitles first
      if (audioUrl === 'youtube-player') {
        // Use the new unified endpoint
        const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL || 'https://yt-dl.onrender.com';
        const response = await fetch(`${backendUrl}/extract-youtube-content`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ 
            url: videoUrl,
            preferCaptions: true 
          })
        });

        const contentType = response.headers.get('content-type');
        
        if (response.ok) {
          // Check if response is JSON
          if (contentType && contentType.includes('application/json')) {
            const data = await response.json();
            
            if (data.success && data.transcript && data.transcript.length > 0) {
              console.log(`Found ${data.isAutoGenerated ? 'auto-generated' : 'manual'} subtitles using ${data.method}`);
              console.log(`Language: ${data.language}, Transcript count: ${data.transcript.length}`);
              setStatus('completed');
              onTranscriptLoaded(data.transcript);
              return;
            } else if (data.methods) {
              // No captions found, show what was tried
              let errorMessage = 'No Japanese captions found for this video.\n\n';
              errorMessage += 'Methods tried:\n';
              
              if (data.methods.youtubeApi) {
                errorMessage += `• YouTube API: ${data.methods.youtubeApi.error || 'No captions'}\n`;
              }
              if (data.methods.ytDlpSubtitles) {
                errorMessage += `• yt-dlp: ${data.methods.ytDlpSubtitles.error || 'No subtitles'}\n`;
              }
              
              console.log('No captions found:', data);
              setStatus('error');
              setError(errorMessage);
              return;
            }
          } else {
            // HTML response, likely an error page
            console.error('Received HTML instead of JSON, likely a 404 or server error');
            setStatus('error');
            setError('Service temporarily unavailable. Please try uploading audio or subtitles manually.');
            return;
          }
        } else {
          if (contentType && contentType.includes('text/html')) {
            console.error('Server returned HTML error page');
            setStatus('error');
            setError('Service temporarily unavailable. The server may be restarting.');
          } else {
            const errorText = await response.text();
            console.error('Failed to extract subtitles:', errorText);
            setStatus('error');
            setError('Failed to connect to subtitle extraction service');
          }
          return;
        }
        
        // Fallback to placeholder if subtitle extraction fails
        const placeholderTranscript: TranscriptLine[] = [
          {
            id: '1',
            text: 'この動画には日本語字幕がありません。',
            startTime: 0,
            endTime: 3,
            words: ['この動画には', '日本語字幕が', 'ありません']
          },
          {
            id: '2',
            text: '音声をアップロードしてAIで文字起こしすることができます。',
            startTime: 3,
            endTime: 6,
            words: ['音声を', 'アップロードして', 'AIで', '文字起こし', 'することができます']
          }
        ];
        
        setStatus('completed');
        onTranscriptLoaded(placeholderTranscript);
        return;
      }
      
      // Call the Whisper transcription API for regular audio URLs
      const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL || 'https://yt-dl.onrender.com';
      const response = await fetch(`${backendUrl}/transcribe-audio`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          audioUrl: audioUrl,
          language: 'ja' // Japanese language
        })
      });

      if (!response.ok) {
        const contentType = response.headers.get('content-type');
        let errorMessage = 'Failed to transcribe audio';
        
        if (contentType && contentType.includes('application/json')) {
          const errorData = await response.json();
          errorMessage = errorData.error || errorMessage;
          
          if (response.status === 401) {
            errorMessage = 'OpenAI API key not configured on server. Please contact support.';
          } else if (response.status === 429) {
            errorMessage = 'Rate limit exceeded. Please try again in a few minutes.';
          } else if (errorMessage.includes('API key not configured')) {
            errorMessage = 'The transcription service is not properly configured. Please use manual transcript upload instead.';
          }
        }
        
        throw new Error(errorMessage);
      }

      const data = await response.json();
      
      if (!data.transcript || data.transcript.length === 0) {
        throw new Error('No transcript generated. The audio might be too short or unclear.');
      }

      setStatus('completed');
      onTranscriptLoaded(data.transcript);

    } catch (err) {
      setStatus('error');
      setError(err instanceof Error ? err.message : 'Failed to load transcript');
      console.error('Transcript loading error:', err);
    }
  };

  const retry = () => {
    loadTranscript();
  };

  return (
    <div className="bg-card rounded-lg shadow-sm border border-border p-6">
      <h3 className="font-medium text-foreground mb-4">{strings.youtubeShadowing?.loadingTranscript || 'Loading Transcript'}</h3>
      
      {status === 'loading' && (
        <div className="space-y-3">
          <div className="flex items-center gap-3">
            <svg className="animate-spin h-5 w-5 text-primary" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
            <span className="text-sm text-muted-foreground">
              {audioUrl === 'youtube-player' 
                ? 'Checking for YouTube subtitles...' 
                : (strings.youtubeShadowing?.fetchingTranscript || 'Generating transcript with AI...')}
            </span>
          </div>
          
          <div className="space-y-2">
            {[1, 2, 3].map(i => (
              <div key={i} className="animate-pulse">
                <div className="h-4 bg-muted rounded w-full"></div>
              </div>
            ))}
          </div>
          
          <p className="text-xs text-muted-foreground">
            {audioUrl === 'youtube-player'
              ? 'Looking for manual or auto-generated captions...'
              : (strings.youtubeShadowing?.transcriptNote || 'Using OpenAI Whisper to transcribe Japanese audio. This may take 30-60 seconds...')}
          </p>
        </div>
      )}

      {status === 'completed' && (
        <div className="flex items-center gap-3 text-green-600">
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
          </svg>
          <span className="text-sm">{strings.youtubeShadowing?.transcriptSuccess || 'Transcript loaded successfully!'}</span>
        </div>
      )}

      {status === 'error' && (
        <div className="space-y-3">
          {/* Show SubtitleUploader for YouTube videos */}
          {audioUrl === 'youtube-player' ? (
            <SubtitleUploader onSubtitlesLoaded={onTranscriptLoaded} />
          ) : (
            <>
              <div className="flex items-start gap-3">
                <svg className="w-5 h-5 text-destructive flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <div className="flex-1">
                  <p className="text-sm text-destructive">{error}</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    {strings.youtubeShadowing?.transcriptErrorNote || 'The video might not have captions available'}
                  </p>
                </div>
              </div>
              
              <button
                onClick={retry}
                className="text-sm text-primary hover:text-primary/80 font-medium"
              >
                {strings.youtubeShadowing?.tryAgain || 'Try again'}
              </button>
            </>
          )}
        </div>
      )}

    </div>
  );
}