// Content script that runs on YouTube pages
console.log('Doshi Sensei YouTube Helper loaded');

// Function to extract captions from YouTube's player
async function extractCaptions() {
  try {
    // Method 1: Try to get captions from YouTube's player API
    const player = document.querySelector('#movie_player');
    if (player && player.getPlayerResponse) {
      const playerResponse = player.getPlayerResponse();
      
      if (playerResponse && playerResponse.captions) {
        const captionTracks = playerResponse.captions.playerCaptionsTracklistRenderer?.captionTracks;
        
        if (captionTracks && captionTracks.length > 0) {
          console.log('Found caption tracks:', captionTracks);
          
          // Look for Japanese captions
          const jaTrack = captionTracks.find(track => 
            track.languageCode === 'ja' || 
            track.languageCode === 'ja-JP' ||
            track.vssId?.includes('.ja')
          );
          
          if (jaTrack) {
            // Fetch the actual captions
            const response = await fetch(jaTrack.baseUrl);
            const captionData = await response.text();
            
            return {
              success: true,
              captions: captionData,
              language: jaTrack.languageCode,
              isAutoGenerated: jaTrack.vssId?.includes('.a.') || false,
              trackName: jaTrack.name?.simpleText || 'Japanese'
            };
          }
        }
      }
    }
    
    // Method 2: Try to extract from page's ytInitialPlayerResponse
    const scripts = document.querySelectorAll('script');
    for (const script of scripts) {
      if (script.innerHTML.includes('ytInitialPlayerResponse')) {
        const match = script.innerHTML.match(/var ytInitialPlayerResponse = ({.+?});/);
        if (match) {
          const playerResponse = JSON.parse(match[1]);
          const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
          
          if (captionTracks) {
            const jaTrack = captionTracks.find(track => 
              track.languageCode === 'ja' || 
              track.languageCode === 'ja-JP'
            );
            
            if (jaTrack) {
              const response = await fetch(jaTrack.baseUrl);
              const captionData = await response.text();
              
              return {
                success: true,
                captions: captionData,
                language: jaTrack.languageCode,
                isAutoGenerated: jaTrack.kind === 'asr',
                trackName: jaTrack.name?.simpleText || 'Japanese'
              };
            }
          }
        }
      }
    }
    
    return {
      success: false,
      error: 'No Japanese captions found'
    };
    
  } catch (error) {
    console.error('Error extracting captions:', error);
    return {
      success: false,
      error: error.message
    };
  }
}

// Function to get video info
function getVideoInfo() {
  const videoId = new URLSearchParams(window.location.search).get('v');
  const videoTitle = document.querySelector('h1.ytd-video-primary-info-renderer')?.textContent?.trim() || 
                     document.querySelector('h1.title')?.textContent?.trim() ||
                     document.title.replace(' - YouTube', '');
  
  return {
    videoId,
    videoTitle,
    url: window.location.href
  };
}

// Listen for messages from the extension popup or web app
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'extractCaptions') {
    extractCaptions().then(result => {
      sendResponse({
        ...result,
        videoInfo: getVideoInfo()
      });
    });
    return true; // Keep the message channel open for async response
  } else if (request.action === 'getVideoInfo') {
    sendResponse(getVideoInfo());
  }
});

// Also listen for messages from the web app via window.postMessage
window.addEventListener('message', async (event) => {
  // Only accept messages from trusted origins
  if (event.origin !== 'http://localhost:3000' && 
      event.origin !== 'https://doshisensei.com') {
    return;
  }
  
  if (event.data.type === 'DOSHI_SENSEI_REQUEST_CAPTIONS') {
    const result = await extractCaptions();
    const videoInfo = getVideoInfo();
    
    // Send the result back to the web app
    event.source.postMessage({
      type: 'DOSHI_SENSEI_CAPTIONS_RESPONSE',
      data: {
        ...result,
        videoInfo
      }
    }, event.origin);
  }
});