// Popup script
let currentTab = null;
let videoInfo = null;

// Initialize popup
document.addEventListener('DOMContentLoaded', async () => {
  const statusDiv = document.getElementById('status');
  const extractBtn = document.getElementById('extractBtn');
  const openDoshiBtn = document.getElementById('openDoshiBtn');
  const captionInfoDiv = document.getElementById('captionInfo');
  
  // Get current tab
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  currentTab = tab;
  
  // Check if we're on a YouTube video page
  if (!tab.url || !tab.url.includes('youtube.com/watch')) {
    statusDiv.className = 'status error';
    statusDiv.textContent = 'Please navigate to a YouTube video page';
    return;
  }
  
  // Get video info
  chrome.tabs.sendMessage(tab.id, { action: 'getVideoInfo' }, (response) => {
    if (chrome.runtime.lastError) {
      statusDiv.className = 'status error';
      statusDiv.textContent = 'Could not connect to YouTube page. Please refresh and try again.';
      return;
    }
    
    videoInfo = response;
    statusDiv.className = 'status success';
    statusDiv.innerHTML = `<strong>Video found:</strong><br>${videoInfo.videoTitle}`;
    extractBtn.disabled = false;
    openDoshiBtn.disabled = false;
  });
  
  // Extract captions button
  extractBtn.addEventListener('click', async () => {
    extractBtn.disabled = true;
    extractBtn.innerHTML = '<span class="loading"></span>Extracting...';
    statusDiv.className = 'status info';
    statusDiv.textContent = 'Looking for Japanese captions...';
    
    chrome.tabs.sendMessage(currentTab.id, { action: 'extractCaptions' }, (response) => {
      extractBtn.disabled = false;
      extractBtn.textContent = 'Extract Captions';
      
      if (chrome.runtime.lastError) {
        statusDiv.className = 'status error';
        statusDiv.textContent = 'Error: ' + chrome.runtime.lastError.message;
        return;
      }
      
      if (response.success) {
        statusDiv.className = 'status success';
        statusDiv.innerHTML = `<strong>Captions found!</strong><br>Language: ${response.language}`;
        captionInfoDiv.textContent = `Type: ${response.isAutoGenerated ? 'Auto-generated' : 'Manual'} | Track: ${response.trackName}`;
        
        // Store captions in local storage for the web app to retrieve
        chrome.storage.local.set({
          latestCaptions: {
            videoInfo: response.videoInfo,
            captions: response.captions,
            language: response.language,
            isAutoGenerated: response.isAutoGenerated,
            timestamp: Date.now()
          }
        });
        
        // Automatically open in Doshi Sensei
        setTimeout(() => {
          openDoshiBtn.click();
        }, 1000);
      } else {
        statusDiv.className = 'status error';
        statusDiv.textContent = 'No Japanese captions found';
        captionInfoDiv.textContent = 'Try uploading audio or subtitles manually in Doshi Sensei';
      }
    });
  });
  
  // Open in Doshi Sensei button
  openDoshiBtn.addEventListener('click', () => {
    if (videoInfo) {
      chrome.runtime.sendMessage({
        action: 'openDoshiSensei',
        url: videoInfo.url
      });
      window.close();
    }
  });
});